sudo: false
language: go
go:
  - 1.7.6
  - 1.8.3
  - 1.9
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test
  - goveralls -service=travis-ci

branches:
  only: [master]
